name: MollyAuction
version: '${version}'
main: ua.nagivka.mollyauction.MollyAuction
author: nagivka
api-version: '1.20'
depend: [Vault]
softdepend: [Oraxen, ItemsAdder, Nexo, PlaceholderAPI]

libraries:
  - com.zaxxer:HikariCP:5.1.0
  - org.xerial:sqlite-jdbc:3.45.2.0
  - net.kyori:adventure-text-minimessage:4.17.0

commands:
  ah:
    description: Главная команда аукциона
    aliases: [auction, mollyauction]

permissions:
  mollyauction.use:
    description: Доступ к просмотру и покупке товаров на аукционе
    default: true
  mollyauction.sell:
    description: Доступ к выставлению предметов на аукцион
    default: true
  mollyauction.admin:
    description: Административные права аукциона
    default: op
  # Совместимость со старыми правами NGVKauction
  ngvkauctions.use:
    default: true
  ngvkauctions.sell:
    default: true
  ngvkauctions.admin:
    default: op